[package]
name = "zzapcho-launcher"
version = "0.7.1"
description = "A compact custom Minecraft launcher"
authors = ["zzapcho"]
edition = "2021"

[lib]
name = "zzapcho_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "blocking"] }
keyring = "3"
mc-launcher-core = "0.1.1"
zip = "2.4"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
discord-rich-presence = "1.1"
tauri-plugin-updater = "2"
tauri-plugin-window-state = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
